# file=open("file.txt","a+")
# file.write("and dosa too")
# file.seek(0)
# data=file.read()
# print(data)
# file.close()
# f = open("file.txt", "w")
# f.write("Hello, this is Python file handling.\n")
# f.write("This file is created using write mode.")
# f.close()
# f = open("file.txt", "r")
# content = f.read()
# print(content)
# f.close()
f = open("file.txt", "r")
lines = f.readlines()
print(lines)
f.close()